<a href="https://colab.research.google.com/github/AynaAraujo/Aprendendo_Redes_Neurais/blob/main/Sintaxe_do_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Sintaxe do Pytorch:
https://pytorch.org/docs/stable/tensors.html

###Tipos de Tensores

In [ ]:
import torch

lista = [[1,2,3],
         [4,5,6]]

#Convertendo pra tensor
tns = torch.Tensor(lista)
print(tns.dtype)
print(tns)

print('--'*20)

tns = torch.FloatTensor(lista)
print(tns.dtype)
print(tns)
print('--'*20)

tns = torch.DoubleTensor(lista)
print(tns.dtype)
print(tns)
print('--'*20)
tns = torch.LongTensor(lista)
print(tns.dtype)
print(tns)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
----------------------------------------
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
----------------------------------------
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
----------------------------------------
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


###Outras formas de instanciar tensores

####**A partir de arrays Numpy**

*torch.from_numpy()*

In [ ]:
import numpy as np

arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)

print(arr)
print(arr.dtype)
print('--'*20)
print(tns)
print(tns.dtype)

#O tensor preserva o tipo original dos dados

[[0.27419906 0.54578596 0.92437986 0.45851515]
 [0.10167202 0.99429375 0.79720758 0.12263522]
 [0.52932988 0.45737376 0.4256361  0.83317553]]
float64
----------------------------------------
tensor([[0.2742, 0.5458, 0.9244, 0.4585],
        [0.1017, 0.9943, 0.7972, 0.1226],
        [0.5293, 0.4574, 0.4256, 0.8332]], dtype=torch.float64)
torch.float64


####**Tensores inicializados**

*torch.zeros()*-> Cria um tensor preenchido com zeros

*torch.ones()*-> Cria um tensor preenchido com uns

*torch.randn()*-> Cria um tensor preenchido com números aleatórios

In [ ]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)


print(tns1)
print('--'*20)
print(tns0)
print('--'*20)
print(tnsr)
print('--'*20)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
----------------------------------------
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
----------------------------------------
tensor([[ 0.1593,  0.1685,  0.7305],
        [ 0.0833,  0.7794, -0.4341],
        [-0.3386, -0.7693,  0.9574]])
----------------------------------------


####**Tensor para array numpy**

In [ ]:
arr = tnsr.data.numpy() #Isola o atributo data
print(arr)
print(type(arr))
print(type(tnsr))

[[ 0.15930939  0.1684736   0.73051596]
 [ 0.08325286  0.77937555 -0.43409115]
 [-0.33855367 -0.76931053  0.95741284]]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


####**Indexação**

In [ ]:
print(tnsr)
#Pegando um valor específico do tensor(index)
tnsr[0,2] = -10

print('--'*20)

print(tnsr)

tensor([[ 0.1593,  0.1685,  0.7305],
        [ 0.0833,  0.7794, -0.4341],
        [-0.3386, -0.7693,  0.9574]])
----------------------------------------
tensor([[  0.1593,   0.1685, -10.0000],
        [  0.0833,   0.7794,  -0.4341],
        [ -0.3386,  -0.7693,   0.9574]])


In [ ]:
print(tnsr[0:2])
print('--'*20)
print(tnsr[:,2])
print('--'*20)
print(tnsr[0,2])
print(tnsr[0,2].size())

tensor([[  0.1593,   0.1685, -10.0000],
        [  0.0833,   0.7794,  -0.4341]])
----------------------------------------
tensor([-10.0000,  -0.4341,   0.9574])
----------------------------------------
tensor(-10.)
torch.Size([])


###**Operações com Tensores**

*.item()* -->Returns the value of this tensor as a standard Python number. This only works for tensors with one element.

In [ ]:
print(tnsr.shape)
print(tns1.shape)
#Não tem a mesma dimensão
print('--'*10)
tns = tnsr [0:2,:]
print(tns.shape)
print(tns1.shape)

torch.Size([3, 3])
torch.Size([2, 3])
--------------------
torch.Size([2, 3])
torch.Size([2, 3])


In [ ]:
print(tns)
print(tns1)

tensor([[  0.1593,   0.1685, -10.0000],
        [  0.0833,   0.7794,  -0.4341]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [ ]:
#Operações
print(tns + tns1)

print(tns * tns1)#MULTIPLICAÇÃO ESCALAR!

print(tns / tns1)

tensor([[ 1.1593,  1.1685, -9.0000],
        [ 1.0833,  1.7794,  0.5659]])
tensor([[  0.1593,   0.1685, -10.0000],
        [  0.0833,   0.7794,  -0.4341]])
tensor([[  0.1593,   0.1685, -10.0000],
        [  0.0833,   0.7794,  -0.4341]])


In [ ]:
#Multiplicação entre matrizes
print(torch.mm(tns1,tns.T))#Como a qtd de linhas da 1 tem q ser igual a qtd de colunas da segunda precisamos transpor umas

tensor([[-9.6722,  0.4285],
        [-9.6722,  0.4285]])


###**Função .size() e .view()**

In [ ]:
print(tns1.size()) #Nesse caso ele retorna um objeto
print('--'*20)

tns= torch.randn(2,2,3)
print(tns)
print('--'*20)

tns_01 = tns.view(12) #Redimensionou
print(tns_01)

print('--'*20)
tns_1 = tns.view(-1)
print(tns_1)

torch.Size([2, 3])
----------------------------------------
tensor([[[ 0.1872, -0.6120, -0.0079],
         [-1.2824, -1.3017, -1.0982]],

        [[-1.0835,  1.1613, -0.8021],
         [ 0.4638, -0.8882,  0.0688]]])
----------------------------------------
tensor([ 0.1872, -0.6120, -0.0079, -1.2824, -1.3017, -1.0982, -1.0835,  1.1613,
        -0.8021,  0.4638, -0.8882,  0.0688])
----------------------------------------
tensor([ 0.1872, -0.6120, -0.0079, -1.2824, -1.3017, -1.0982, -1.0835,  1.1613,
        -0.8021,  0.4638, -0.8882,  0.0688])


##**GPU Cast**

In [ ]:
if torch.cuda.is_available():
  device = torch.device('cuda')
else:
  device = torch.device('cpu')

print(device)

cuda


In [ ]:
#Jogando var no GPU
tns = tns.to(device)
print(tns)

tensor([[[ 0.1872, -0.6120, -0.0079],
         [-1.2824, -1.3017, -1.0982]],

        [[-1.0835,  1.1613, -0.8021],
         [ 0.4638, -0.8882,  0.0688]]], device='cuda:0')
